# Generated by Django 5.2.7 on 2025-10-02 00:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('es_activa', models.BooleanField(default=True)),
                ('id_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('valida_hasta', models.DateField()),
                ('subtotal_antes_impuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('porcentaje_impuestos', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('valor_impuestos_calculado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mostrar_impuestos_desglosados', models.BooleanField(default=False)),
                ('condiciones_comerciales', models.TextField(blank=True)),
                ('tiempos_entrega', models.TextField(blank=True)),
                ('garantia', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intermediario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('datos_pago', models.TextField(blank=True, help_text='Información para liquidación de comisiones')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('costo_adquisicion', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_venta_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_agrupada', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizador.cotizacion')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizador.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.proveedor'),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Remodelación Apartamento 701', max_length=255)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(default='En Diseño', max_length=50)),
                ('porcentaje_comision_interna', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('valor_comision_calculada', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('estado_comision', models.CharField(default='PENDIENTE', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.cliente')),
                ('intermediario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.intermediario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleItemProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_manual', models.CharField(blank=True, max_length=255)),
                ('precio_unitario_capturado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('espacio', models.CharField(help_text='Ej: Cocina', max_length=200)),
                ('sub_espacio', models.CharField(blank=True, help_text='Ej: Isla Central', max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color_carcaza', models.CharField(blank=True, max_length=100)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizador.producto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cotizador.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.proyecto'),
        ),
    ]
