# Generated by Django 5.2.7 on 2025-10-06 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='digito_verificacion',
            field=models.CharField(blank=True, max_length=1, validators=[django.core.validators.RegexValidator('^\\d{1}$', 'El dígito de verificación debe ser un solo número.')], verbose_name='DV'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
