# Generated by Django 5.2.7 on 2025-10-06 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_cliente_digito_verificacion_cliente_nit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsabilidadFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nit',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('PERSONA', 'Persona'), ('EMPRESA', 'Empresa')], default='PERSONA', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('NIT', 'NIT'), ('CC', 'Cédula de ciudadanía')], max_length=5),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='digito_verificacion',
            field=models.CharField(blank=True, max_length=1, verbose_name='DV'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='cotizador.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='responsabilidades_fiscales',
            field=models.ManyToManyField(blank=True, to='cotizador.responsabilidadfiscal'),
        ),
    ]
