# Generated by Django 5.2.7 on 2025-11-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0003_responsabilidadfiscal_remove_cliente_nit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='apellidos',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='digito_verificacion',
            field=models.CharField(blank=True, max_length=1, verbose_name='DV'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='identificacion',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombres',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='responsabilidades_fiscales',
            field=models.ManyToManyField(blank=True, to='cotizador.responsabilidadfiscal'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo',
            field=models.CharField(choices=[('PERSONA', 'Persona'), ('EMPRESA', 'Empresa')], default='EMPRESA', max_length=10),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('NIT', 'NIT'), ('CC', 'Cédula de ciudadanía')], max_length=5),
        ),
    ]
