# Generated by Django 5.2.7 on 2025-11-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0004_remove_proveedor_contacto_remove_proveedor_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleitemproyecto',
            name='garantia_especifica_meses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Garantía (meses)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='garantia_default_meses',
            field=models.PositiveIntegerField(default=12, verbose_name='Garantía (meses)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_actual',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
