# Generated by Django 5.2.7 on 2025-11-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0005_detalleitemproyecto_garantia_especifica_meses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('DISEÑO', 'En Diseño'), ('COTIZADO', 'Cotizado'), ('APROBADO', 'Aprobado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='DISEÑO', max_length=50),
        ),
    ]
