# Generated by Django 5.2.7 on 2025-11-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0006_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacion',
            name='garantia_meses',
            field=models.PositiveIntegerField(default=0, verbose_name='Garantía (meses)'),
        ),
    ]
