# Generated by Django 5.2.7 on 2025-11-23 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0007_itemcotizacion_garantia_meses'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Ej: 50 para 50%', max_digits=5)),
                ('valor', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('descripcion', models.CharField(help_text='Ej: Anticipo para compra de materiales', max_length=255)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cotizador.cotizacion')),
            ],
        ),
    ]
