# Generated by Django 5.2.7 on 2025-12-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0008_hitopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='moneda',
            field=models.CharField(choices=[('COP', 'Pesos Colombianos'), ('USD', 'Dólares Americanos')], default='COP', max_length=3),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='trm',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Si es COP, dejar en 1. Si es USD, colocar la tasa del día.', max_digits=10, verbose_name='TRM (Tasa de cambio)'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='condiciones_comerciales',
            field=models.TextField(blank=True, default='1. Forma de pago: 50% anticipo y 50% contra entrega.\n2. La validez de la oferta es de 15 días.\n3. Los precios incluyen IVA.'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='garantia',
            field=models.TextField(blank=True, default='Garantía de 1 año por defectos de fabricación e instalación.'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='tiempos_entrega',
            field=models.TextField(blank=True, default='Tiempo de entrega: 3 a 5 días hábiles después de recibido el anticipo.'),
        ),
        migrations.AlterField(
            model_name='hitopago',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
