# Generated by Django 5.2.7 on 2025-12-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0009_cotizacion_moneda_cotizacion_trm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='trm',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='TRM (Tasa de cambio)'),
        ),
    ]
