# Generated by Django 5.2.7 on 2025-12-03 04:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0010_alter_cotizacion_trm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('conductor', models.CharField(blank=True, max_length=200)),
                ('placa_vehiculo', models.CharField(blank=True, max_length=20)),
                ('empresa_transportadora', models.CharField(blank=True, max_length=200)),
                ('recibido_por', models.CharField(blank=True, max_length=200)),
                ('identificacion_receptor', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remisiones', to='cotizador.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_variable', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.producto')),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_remision', to='cotizador.remision')),
            ],
        ),
    ]
