# Generated by Django 5.2.7 on 2025-12-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0011_remision_itemremision'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemremision',
            name='espacio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='itemremision',
            name='sub_espacio',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
